### ISSUE TITLE
Blindly adding config to mysite.yml doesn't work

### ISSUE THREAD

**Issue by sminnee** [silverstripe/recipe-core#1]
When you open up a site created from this recipe, and chuck in some config, you'll probably put it into the bottom of mysite.yml

The problem is that this doesn't work — the config clause in there is set to Before: coreconfig which behaves differently from what you'd expect.

This is a developer-experience bug.

This could be solved in a couple of ways:

 * Consider whether the before rule is actually necessary? I don't see why it would be...
 * Add a second, separate config section that doesn't have a special before rule, so that people's custom config will go in there
 * Add a separate (empty) config.yml which is where people's site config should be added, leaving mysite.yml as a special piece of project plumbing

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/recipe-core/pull/3
