### ISSUE TITLE
Webconfig issues with rewriting module

### ISSUE THREAD

**Issue by adrhumphreys** [silverstripe/recipe-core#18]
Could be that our server is set up incorrectly but if we don;t add the following rewrite rule to our webconfig then the site will 404 on anything other than / (e.g. /admin will 404)

```
<rewrite>
       <rules>
         <rule name="SilverStripe Clean URLs" stopProcessing="true">
           <match url="^(.*)$" />
           <conditions>
             <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
           </conditions>
           <action type="Rewrite" url="index.php?url={R:1}" appendQueryString="true" />
          </rule>
        </rules>
      </rewrite>
```

# PRs:

- [x] https://github.com/silverstripe/recipe-core/pull/21
- [x] https://github.com/silverstripe/recipe-core/pull/22

**Comment by chillu** [comment]
Framework version? IIS version? Where did you get the standard `web.config` from? Can you post it here? Are there any other modifications?

**Comment by chillu** [comment]
@adrhumphreys We need more info on this

**Comment by adrhumphreys** [comment]
@chillu sorry about the delay have been busy recently. The standard ```web.config``` is from this repo, the version of IIS is 8.5, Framework is just SS4 using this recipe. This is the only modification that I needed

**Comment by chillu** [comment]
@tractorcow I think you've done the IIS testing for SS4 after the public webroot changes in 4.1. It seems strange that the `web.config` in `recipe-core` doesn't have any rewrite rules - or would that file be overwritten? https://github.com/silverstripe/recipe-core/blob/1.0/web.config. It's marked as the file to be copied into the project root, see https://github.com/silverstripe/recipe-core/blob/1.0/composer.json#L20

**Comment by tractorcow** [comment]
Yes I recall something about needing to run the installer once to rewrite it dynamically. We could probably plop in a standard ruleset for the recipe.
