### ISSUE TITLE
When you are not using standard project path, composer install duplicates files

### ISSUE THREAD

**Issue by sminnee** [silverstripe/recipe-core#23]
If you're using recipe 1.1 (projectpath = mysite) and you have a project with projectpath = app, then running composer install will re-initialise the mysite folder, creating duplicate files.

This occurred after taking a project and upgrading it with the `upgrade-code recompose` command.

**Comment by chillu** [comment]
This results in very opaque fatal errors after an upgrade to 4.2:

> Fatal error: Uncaught Exception: More than one YAML document exists named 'mywidgetsconfig' in '/var/www/mysite/www/mysite/_config/blog.yml' and '/var/www/mysite/www/app/_config/blog.yml' in /var/www/mysite/www/vendor/silverstripe/config/src/Transformer/YamlTransformer.php on line 216

A *lot* of devs will hit this when just running a `composer update` on a stable minor release constraint, assuming they don't need to worry too much about upgrading guides in minor releases.

https://docs.silverstripe.org/en/4/changelogs/4.2.0/ says:

> The standard 'mysite' code naming convention has changed in 4.2. Although existing sites can continue to use 'mysite/code` to store their base project code, the recommendation and new default is to store code in app/src.

They can "continue to use mysite" if they figure out this weird fatal error. That's not a great upgrade experience.

We can solve this a few different ways:
 * Scan for `SilverStripe\Core\Manifest\ModuleManifest.project` YAML config and use that. With a fallback to `$project` defined in PHP?
 * Scan for files with the same name in a different directory structure (e.g. `Page.php`). That gets difficult with files like `app/_config/mysite.yml`.

None of these is a good way forward IMHO

Aside: `app/_config/mysite.yml` hasn't been renamed to `app/_config/app.yml`. That's a difficult one to do with the limited means of `vendor-plugin`. If we just naively rename the file in the 4.2.0 recipe, it'll create a duplicate, with confusing results for developers (duplicate YAML keys and weird errors)

**Comment by chillu** [comment]
So after all this, turns out the mighty @tractorcow has tackled this already, but hadn't tagged a release ;) https://github.com/silverstripe/recipe-plugin/pull/7. I've now tagged a 1.3.0.
