### ISSUE TITLE
Add Travis builds

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/recipe-core#29]
The optional SilverStripe recipes (form building, collaboration etc) have all got Travis builds which run the test suites of the modules contained within the recipes. This helps us (A) to know that integration test suites are passing, and (B) to know that any config or project files we add work in context.

We should add Travis builds to this repository and the CMS

**Comment by robbieaverill** [comment]
PR at #30

**Comment by GuySartorelli** [comment]
Closed - that PR was merged and we've since removed travis in favor of github actions
