### ISSUE TITLE
Delete the 1 branch

### ISSUE THREAD

**Issue by sminnee** [silverstripe/recipe-core#37]
Recipe 1.x is deprecated. The current tags should be retained to avoid breaking people's sites, but no new releases should be made. As such I think we should delete the `1`, `1.0`, and `1.1` branches.

**Comment by sminnee** [comment]
Related: https://github.com/silverstripe/recipe-cms/issues/24

**Comment by maxime-rainville** [comment]
Let's keep all the discussion on silverstripe/recipe-cms#24. There's no universe where we would treat recip-core differently then recipe-cms.
