### ISSUE TITLE
Clean up .htaccess (and possibly web.config)

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/recipe-core#42]
I noticed that the current `.htaccess` file which bootstraps requests to `index.php` looks like this (near bottom):

```apacheconf
# Process through SilverStripe if no file with the requested name exists.
# Pass through the original path as a query parameter, and retain the existing parameters.
# Try finding framework in the vendor folder first
RewriteCond %{REQUEST_URI} ^(.*)$
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule .* index.php
```
However, the path is no longer being passed as a parameter, therefore there is no longer any need to have the `RewriteCond` that applies a RegEx capturing group to `%{REQUEST_URI}`. Also, the comments are out of date. This is probably just legacy from earlier versions of SS. I'd propose trimming this down for simplicity to:

```apacheconf
# Process through SilverStripe if no file with the requested name exists.
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule .* index.php
```

**Comment by patricknelson** [comment]
See #43

**Comment by chillu** [comment]
+1, good catch. Is that the case in all variations of running PHP? mod_php, php-fpm, cgi, etc

**Comment by patricknelson** [comment]
Not sure how this impacts `mod_php` (which is an Apache module, part of the same Apache that `.htaccess` already is configuring`) or `php-fpm` which would be controlled separately as well. The only concern I'd have is with `web.config` (not mentioned) which I don't understand; however, the only loose end I see there is the use of `appendQueryString="true"` which seems to be similar to `.htaccess`'s `[QSA]` configuration that I know was intentionally dropped.

Thoughts on that? :D
